// remote4/src/components/Navigation.jsx
import { Link, useNavigate, createSearchParams } from "react-router-dom";

const Navigation = () => {
  const navigate = useNavigate();

  const handleClick = () => {
    const id = (Math.random() * 100).toFixed();
    const search = createSearchParams({ id }).toString();
    navigate({ replace: true, pathname: "/remote4/page", search });
  };

  return (
    <div>
      <hr />
      <Link to="/">Host: Home</Link>
      <br />
      <Link to="/page">Host: Page</Link>
      <br />
      <br />
      <Link to="/remote4">Remote4: Home</Link>
      <br />
      <Link to="/remote4/page">Remote4: Page</Link>
      <br />
      <br />
      <button onClick={handleClick}>Replace method</button>
    </div>
  );
};

export default Navigation;

// remote3/src/components/Navigation.vue
<template>
  <div>
    <hr />
    <router-link to="/">Host: Home</router-link>
    <br />
    <router-link to="/page">Host: Page</router-link>
    <br />
    <br />
    <router-link to="/remote3">Remote3: Home</router-link>
    <br />
    <router-link to="/remote3/page">Remote3: Page</router-link>
    <br />
    <br />
    <button @click="handleClick">Replace method</button>
  </div>
</template>

<script>
export default {
  name: 'Navigation',
  methods: {
    handleClick() {
      const id = (Math.random() * 100).toFixed()
      this.$router.replace(`/remote3/page/?id=${id}`)
    }
  }
}
</script>
